version: "3.9"

services:
  login_node_dev:
    container_name: login_node_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    networks:
      - login_users_api_dev
    volumes:
      - .:/var/www/html/loginApp

  login_psql_dev:
    container_name: login_psql_dev
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=users_dev
      - POSTGRES_USER=leonardo
      - POSTGRES_PASSWORD=TooR
    volumes:
      - ./config/Postgres/dev.sql:/docker-entrypoint-initdb.d/dev.sql
      - data-postgres_dev:/var/lib/postgresql/data-postgres_dev
    networks:
      - login_users_api_dev

networks:
  login_users_api_dev:

volumes:
  data-postgres_dev: