### GET ALL USERS
GET http://localhost:3000/user

### CREATE USER

POST http://localhost:3000/user
Content-Type: application/json

{
  "document_type": "CC",
  "document_number": 1000003,
  "first_name": "Daniel",
  "last_name": "Ruiz",
  "age": 24,
  "birthdate": "2020-10-10",
	"email":"daniel@gmail.com",
	"user_password":"password2"
}

### UPDATE USER
PATCH http://localhost:3000/user/1000003
Content-Type: application/json

{
  "first_name": "su mama",
  "user_password": "otramama"
}

### DELETE USER

DELETE http://localhost:3000/user/1000003
